clear all;
% %%%pdf figures of downtime distribution generated by Gamma approximation and monte carlo simulation
% sample = 10000;
% for n=1:sample
%     d(n)= downunin(5);
% end
%  [f,xi] = ksdensity(d);
%  %[h,x] = hist(d,100);
%  figure()
%  plot(xi,f,'LineStyle','-.');
%  %bar (x, h./sum(h)); 
%   hold on
%   Downtimegamman(5); 
%   hold off


%%%pdf figures of exceed downtime generated by Gamma approximation and monte carlo simulation
sample = 10000;
for n=1:sample
    d(n)= exdownunisn(50,0.4,1.1);
    display(n);
end
 %figure()
 avg_s = mean(d);
 display(avg_s);
 
 
 histnorm(d,50,'plot');
%  histfit(d);
%  bar (x, h./trapz(x,h)); 
%  bar (x, h./sum(x,h));
  hold on
  exdowntimegamman(5,0.2,1); 
  hold off


%  for n=1:1000
%     d(n)= MCNN(20);
% end
%  [h,x] = hist(d,20);
%  bar (x, h./trapz(x,h)); 
% %  hold on
% % %  DowntimeGn(20); hold off
%  for n=1:1000
%     d(n)= downMC(0.5,2.5,0.4,2);
%  end
%  [h,x] = hist(d,100);
%  bar (x, h./trapz(x,h)); 
%  hold on
%  DowntimeGn(2); hold off

%  for n=1:100
%      d(n)= downtime1(0.4,1.5);
%      display(n);
%  end
%   [h,x] = hist(d,10);
%   bar (x, h./trapz(x,h)); 
%   hold on
%   DowntimeG1(0.4,1.5); hold off

% sample = 10000;
% for n=1:sample
%     d(n)= exdownunisn(5,0.2,1);
%     display(n);
% end
%  %figure()
%  avg_s = mean(d);
%  display(avg_s);
%  avg_a = Downtimegammanexceed(5,0.2,1);


















